### ISSUE TITLE
Alan's TODOs

### ISSUE THREAD

**Issue by PatPatKittyKat** [PatPatKittyKat/SLP-website#2]
**Small Visual Fix**
- [x] Line up col borders in about.html and contact.html
- When users navigate between these two pages, they will see the dividing line jump.

**Background Style Decisions**
- [x] Should we divide pages using col-sm-8 & col-sm-4 for all top menu pages (except index.html)?

**Match background page styles for top menu pages**
1. about.html has `<div id="about" class="container-fluid sideMargins">`
2. contact.html has `<div id="contact" class="container-fluid bg-grey sideMargins">`
3. SUGGESTION:
- [x] in about.html, change above tag to: `<div id="about" class="container-fluid bg-grey sideMargins">`
- [x] remove extra grey in the margins of the contact info at the bottom of about.html
- [x] update all other top-menu pages with this background format (EXCEPT index.html)

**Comment by AlanCooper509** [comment]
Made appropriate changes,

>Aligning about.html and contact.html turned out to be a hassle since "ABOUT LJHC" is a single header whereas "OUR LOCATION" and "CONTACT LJHC" are two separate headers on the same line... tried to adjust for about an hour by messing with col-sm-12, col-sm-8, col-sm-4, the "row" class, etc. before giving up and deciding to just remove the border between the two.

>I think having elements side by side col-sm-8 and col-sm-4 on sub-pages is good, especially since it makes the desktop version look more space-filling and less bland. This seems to translate easily to the mobile version as well.

>After updating to add side-margins to all sub-pages, the footer seems out of place. I suggest doing something similar to what was done for texastasa.com, where the footer color matches the header color and more content is placed within the footer itself, instead of just the chevron arrow leading back up to the top of the webpage.
